
stock_data = [
    {"symbol": "AAPL", "description": "Apple Inc."},
    {"symbol": "MSFT", "description": "Microsoft Corporation"},
    {"symbol": "AMZN", "description": "Amazon.com, Inc."},
    {"symbol": "GOOGL", "description": "Alphabet Inc."},
    {"symbol": "TSLA", "description": "Tesla, Inc."},
    {"symbol": "V", "description": "Visa Inc."},
    {"symbol": "JPM", "description": "JPMorgan Chase & Co."},
    {"symbol": "JNJ", "description": "Johnson & Johnson"},
    {"symbol": "WMT", "description": "Walmart Inc."},
    {"symbol": "PG", "description": "Procter & Gamble Co."},
    {"symbol": "MA", "description": "Mastercard Incorporated"},
    {"symbol": "NVDA", "description": "NVIDIA Corporation"},
    {"symbol": "HD", "description": "The Home Depot, Inc."},
    {"symbol": "PYPL", "description": "PayPal Holdings, Inc."},
    {"symbol": "DIS", "description": "The Walt Disney Company"},
    {"symbol": "BAC", "description": "Bank of America Corporation"},
    {"symbol": "VZ", "description": "Verizon Communications Inc."},
    {"symbol": "CMCSA", "description": "Comcast Corporation"},
    {"symbol": "KO", "description": "The Coca-Cola Company"},
    {"symbol": "NFLX", "description": "Netflix, Inc."},
    {"symbol": "T", "description": "AT&T Inc."},
    {"symbol": "PFE", "description": "Pfizer Inc."},
    {"symbol": "INTC", "description": "Intel Corporation"},
    {"symbol": "MRK", "description": "Merck & Co., Inc."},
    {"symbol": "PEP", "description": "PepsiCo, Inc."},
    {"symbol": "CSCO", "description": "Cisco Systems, Inc."},
    {"symbol": "ORCL", "description": "Oracle Corporation"},
    {"symbol": "ABT", "description": "Abbott Laboratories"},
    {"symbol": "FB", "description": "Facebook, Inc."},
    {"symbol": "BRK-A", "description": "Berkshire Hathaway Inc."},
    {"symbol": "TSM", "description": "Taiwan Semiconductor Manufacturing Company Limited"},
    {"symbol": "NVZMY", "description": "Novartis AG"},
    {"symbol": "NKE", "description": "Nike, Inc."},
    {"symbol": "UNH", "description": "UnitedHealth Group Incorporated"},
    {"symbol": "ADBE", "description": "Adobe Inc."},
    {"symbol": "CRM", "description": "Salesforce.com, Inc."},
    {"symbol": "MCD", "description": "McDonald's Corporation"},
    {"symbol": "TMO", "description": "Thermo Fisher Scientific Inc."},
    {"symbol": "ASML", "description": "ASML Holding N.V."},
    {"symbol": "XOM", "description": "Exxon Mobil Corporation"},
    {"symbol": "CVX", "description": "Chevron Corporation"},
    {"symbol": "BABA", "description": "Alibaba Group Holding Limited"},
    {"symbol": "TM", "description": "Toyota Motor Corporation"},
    {"symbol": "ABBV", "description": "AbbVie Inc."},
    {"symbol": "AMGN", "description": "Amgen Inc."},
    {"symbol": "WFC", "description": "Wells Fargo & Company"},
    {"symbol": "LMT", "description": "Lockheed Martin Corporation"},
    {"symbol": "GOOG", "description": "Alphabet Inc."},
    {"symbol": "XOM", "description": "Exxon Mobil Corporation"},
    {"symbol": "KO", "description": "The Coca-Cola Company"},
    {"symbol": "NFLX", "description": "Netflix, Inc."},
    {"symbol": "T", "description": "AT&T Inc."},
    {"symbol": "PFE", "description": "Pfizer Inc."},
    {"symbol": "INTC", "description": "Intel Corporation"},
    {"symbol": "MRK", "description": "Merck & Co., Inc."},
    {"symbol": "PEP", "description": "PepsiCo, Inc."},
    {"symbol": "CSCO", "description": "Cisco Systems, Inc."},
    {"symbol": "ORCL", "description": "Oracle Corporation"},
    {"symbol": "ABT", "description": "Abbott Laboratories"},
    {"symbol": "FB", "description": "Facebook, Inc."},
    {"symbol": "BRK-A", "description": "Berkshire Hathaway Inc."},
    {"symbol": "TSM", "description": "Taiwan Semiconductor Manufacturing Company Limited"},
    {"symbol": "NVZMY", "description": "Novartis AG"},
    {"symbol": "NKE", "description": "Nike, Inc."},
    {"symbol": "UNH", "description": "UnitedHealth Group Incorporated"},
    {"symbol": "ADBE", "description": "Adobe Inc."},
    {"symbol": "CRM", "description": "Salesforce.com, Inc."},
    {"symbol": "MCD", "description": "McDonald's Corporation"},
    {"symbol": "TMO", "description": "Thermo Fisher Scientific Inc."},
    {"symbol": "ASML", "description": "ASML Holding N.V."},
    {"symbol": "XOM", "description": "Exxon Mobil Corporation"},
    {"symbol": "CVX", "description": "Chevron Corporation"},
    {"symbol": "BABA", "description": "Alibaba Group Holding Limited"},
    {"symbol": "TM", "description": "Toyota Motor Corporation"},
    {"symbol": "ABBV", "description": "AbbVie Inc."},
    {"symbol": "AMGN", "description": "Amgen Inc."},
    {"symbol": "WFC", "description": "Wells Fargo & Company"},
    {"symbol": "LMT", "description": "Lockheed Martin Corporation"},
    {"symbol": "GOOG", "description": "Alphabet Inc."},
    {"symbol": "ADSK", "description": "Autodesk, Inc."},
    {"symbol": "NVAX", "description": "Novavax, Inc."},
    {"symbol": "ZM", "description": "Zoom Video Communications, Inc."},
    {"symbol": "AMD", "description": "Advanced Micro Devices, Inc."},
    {"symbol": "LULU", "description": "Lululemon Athletica Inc."},
    {"symbol": "BA", "description": "The Boeing Company"},
    {"symbol": "UBER", "description": "Uber Technologies, Inc."},
    {"symbol": "SBUX", "description": "Starbucks Corporation"},
    {"symbol": "GS", "description": "The Goldman Sachs Group, Inc."},
    {"symbol": "COST", "description": "Costco Wholesale Corporation"},
    {"symbol": "LOW", "description": "Lowe's Companies, Inc."},
    {"symbol": "F", "description": "Ford Motor Company"},
]