#Magic 60 , with sector info
stock_data = [
    {'Symbol': 'AAPL', 'Security': 'Apple Inc.', 'Sector': 'Technology'}, 
    {'Symbol': 'MSFT', 'Security': 'Microsoft Corporation', 'Sector': 'Technology'},
    {'Symbol': 'AMZN', 'Security': 'Amazon.com, Inc.', 'Sector': 'Consumer Discretionary'}, 
    {'Symbol': 'GOOGL', 'Security': 'Alphabet Inc.', 'Sector': 'Communication Services'},
    {'Symbol': 'TSLA', 'Security': 'Tesla, Inc.', 'Sector': 'Consumer Discretionary'},
    {'Symbol': 'V', 'Security': 'Visa Inc.', 'Sector': 'Financials'}, 
    {'Symbol': 'JPM', 'Security': 'JPMorgan Chase & Co.', 'Sector': 'Financials'},
    {'Symbol': 'JNJ', 'Security': 'Johnson & Johnson', 'Sector': 'Health Care'}, 
    {'Symbol': 'WMT', 'Security': 'Walmart Inc.', 'Sector': 'Consumer Staples'},
    {'Symbol': 'PG', 'Security': 'Procter & Gamble Co.', 'Sector': 'Consumer Staples'},
    {'Symbol': 'MA', 'Security': 'Mastercard Incorporated', 'Sector': 'Financials'},
    {'Symbol': 'NVDA', 'Security': 'NVIDIA Corporation', 'Sector': 'Technology'}, 
    {'Symbol': 'HD', 'Security': 'The Home Depot, Inc.', 'Sector': 'Consumer Discretionary'}, 
    {'Symbol': 'PYPL', 'Security': 'PayPal Holdings, Inc.', 'Sector': 'Financials'}, 
    {'Symbol': 'DIS', 'Security': 'The Walt Disney Company', 'Sector': 'Communication Services'}, 
    {'Symbol': 'BAC', 'Security': 'Bank of America Corporation', 'Sector': 'Financials'},
    {'Symbol': 'VZ', 'Security': 'Verizon Communications Inc.', 'Sector': 'Communication Services'},
    {'Symbol': 'CMCSA', 'Security': 'Comcast Corporation', 'Sector': 'Communication Services'},
    {'Symbol': 'KO', 'Security': 'The Coca-Cola Company', 'Sector': 'Consumer Staples'},
    {'Symbol': 'NFLX', 'Security': 'Netflix, Inc.', 'Sector': 'Communication Services'}, 
    {'Symbol': 'T', 'Security': 'AT&T Inc.', 'Sector': 'Communication Services'}, 
    {'Symbol': 'PFE', 'Security': 'Pfizer Inc.', 'Sector': 'Health Care'}, 
    {'Symbol': 'INTC', 'Security': 'Intel Corporation', 'Sector': 'Technology'},
    {'Symbol': 'MRK', 'Security': 'Merck & Co., Inc.', 'Sector': 'Health Care'},
    {'Symbol': 'PEP', 'Security': 'PepsiCo, Inc.', 'Sector': 'Consumer Staples'}, 
    {'Symbol': 'CSCO', 'Security': 'Cisco Systems, Inc.', 'Sector': 'Technology'},
    {'Symbol': 'ORCL', 'Security': 'Oracle Corporation', 'Sector': 'Technology'}, 
    {'Symbol': 'ABT', 'Security': 'Abbott Laboratories', 'Sector': 'Health Care'}, 
    {'Symbol': 'FB', 'Security': 'Facebook, Inc.', 'Sector': 'Communication Services'},
    {'Symbol': 'TSM', 'Security': 'Taiwan Semiconductor Manufacturing Company Limited', 'Sector': 'Technology'},
    {'Symbol': 'NVZMY', 'Security': 'Novartis AG', 'Sector': 'Health Care'}, 
    {'Symbol': 'NKE', 'Security': 'Nike, Inc.', 'Sector': 'Consumer Discretionary'}, 
    {'Symbol': 'UNH', 'Security': 'UnitedHealth Group Incorporated', 'Sector': 'Health Care'}, 
    {'Symbol': 'ADBE', 'Security': 'Adobe Inc.', 'Sector': 'Technology'}, 
    {'Symbol': 'CRM', 'Security': 'Salesforce.com, Inc.', 'Sector': 'Technology'},
    {'Symbol': 'MCD', 'Security': "McDonald's Corporation", 'Sector': 'Consumer Discretionary'}, 
    {'Symbol': 'TMO', 'Security': 'Thermo Fisher Scientific Inc.', 'Sector': 'Health Care'},
    {'Symbol': 'ASML', 'Security': 'ASML Holding N.V.', 'Sector': 'Technology'}, 
    {'Symbol': 'XOM', 'Security': 'Exxon Mobil Corporation', 'Sector': 'Energy'},
    {'Symbol': 'CVX', 'Security': 'Chevron Corporation', 'Sector': 'Energy'},
    {'Symbol': 'BABA', 'Security': 'Alibaba Group Holding Limited', 'Sector': 'Consumer Discretionary'}, 
    {'Symbol': 'TM', 'Security': 'Toyota Motor Corporation', 'Sector': 'Consumer Discretionary'}, 
    {'Symbol': 'ABBV', 'Security': 'AbbVie Inc.', 'Sector': 'Health Care'},
    {'Symbol': 'AMGN', 'Security': 'Amgen Inc.', 'Sector': 'Health Care'}, 
    {'Symbol': 'WFC', 'Security': 'Wells Fargo & Company', 'Sector': 'Financials'},
    {'Symbol': 'LMT', 'Security': 'Lockheed Martin Corporation', 'Sector': 'Industrials'},
    {'Symbol': 'GOOG', 'Security': 'Alphabet Inc.', 'Sector': 'Communication Services'},
    {'Symbol': 'BRK-A', 'Security': 'Berkshire Hathaway Inc.', 'Sector': 'Financials'},
    {'Symbol': 'ADSK', 'Security': 'Autodesk, Inc.', 'Sector': 'Technology'},
    {'Symbol': 'NVAX', 'Security': 'Novavax, Inc.', 'Sector': 'Health Care'},
    {'Symbol': 'ZM', 'Security': 'Zoom Video Communications, Inc.', 'Sector': 'Technology'},
    {'Symbol': 'AMD', 'Security': 'Advanced Micro Devices, Inc.', 'Sector': 'Technology'},
    {'Symbol': 'LULU', 'Security': 'Lululemon Athletica Inc.', 'Sector': 'Consumer Discretionary'},
    {'Symbol': 'BA', 'Security': 'The Boeing Company', 'Sector': 'Industrials'},
    {'Symbol': 'UBER', 'Security': 'Uber Technologies, Inc.', 'Sector': 'Technology'},
    {'Symbol': 'SBUX', 'Security': 'Starbucks Corporation', 'Sector': 'Consumer Discretionary'},
    {'Symbol': 'GS', 'Security': 'The Goldman Sachs Group, Inc.', 'Sector': 'Financials'},
    {'Symbol': 'COST', 'Security': 'Costco Wholesale Corporation', 'Sector': 'Consumer Staples'}, 
    {'Symbol': 'LOW', 'Security': "Lowe's Companies, Inc.", 'Sector': 'Consumer Discretionary'},
    {'Symbol': 'F', 'Security': 'Ford Motor Company', 'Sector': 'Consumer Discretionary'}
]
