name: Run Alpaca Trading Bot

on:
  schedule:
    - cron: '0 12 * * 1-5'  # run at noon on weekdays
  workflow_dispatch:  # manual trigger

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f AgressiveStockStrat/requirements.txt ]; then pip install -r AgressiveStockStrat/requirements.txt; fi

    - name: Run Alpaca Trading Bot
      run: python AgressiveStockStrat/alpaca_trade.py
